apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: code-challenge-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - environment: dev
      - environment: stage
      - environment: prod
  template:
    metadata:
      name: 'code-challenge-service-{{.environment}}'
    spec:
      project: default
      source:
        chart: code-challenge-service
        repoURL: registry-1.docker.io/davidbour
        targetRevision: 1.0.0-a002f646ced41201fb2f55f68d882e8282ac5078
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'code-challenge-service-{{.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true